export const NOTIFICATION_COPY = {
  app: {
    themeChanged: (label: string) => `${label} theme set.`,
    starRemoved: 'Story removed from starred.',
    starRemoveError: 'Could not update starred entry.',
    feedRefreshing: 'Refreshing feeds...',
    articleMarked: 'Article marked',
    articleUnmarked: 'Article unmarked',
    categoryUpdated: 'Category updated.',
    feedUpdated: 'Feed updated.',
    categoryDeleted: 'Category deleted.',
    feedDeleted: 'Feed deleted.',
    categoryAdded: 'Category added.',
    feedAdded: 'Feed added.',
  },
  demo: {
    defaultToast: 'Saved to reading list.',
    descriptionTitle: 'Feed refreshed.',
    descriptionBody: 'Fetched 12 new items.',
    successToast: 'Category renamed.',
    errorTitle: 'Could not save.',
    errorBody: 'Please try again.',
    actionTitle: 'Feed removed.',
    actionUndoLabel: 'Undo',
    actionUndoResult: 'Undo complete.',
    cancelTitle: 'Discard changes?',
    cancelLabel: 'Keep editing',
    cancelResult: 'Kept editing.',
    loadingTitle: 'Refreshing feeds...',
    loadingSuccess: 'Refresh complete.',
    promiseLoading: 'Syncing library...',
    promiseSuccess: 'Sync complete.',
    promiseError: 'Sync failed.',
    customTitle: 'Saved',
    customBody: 'Added to your "Read later" list.',
  },
} as const;
